name: Deploy Debian Stable
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  deploy-debian-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.3.4
        with:
          path: dienen_behaviors
